# Generated by Django 4.1.7 on 2023-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wind_speed',
            field=models.BigIntegerField(null=True),
        ),
    ]
